<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Chinmaya-84-7B-EB-31-2E-9C" ignored="0" name="Automation" tests="2" failures="1" timestamp="03 Apr 2018 05:26:49 GMT" time="2.503" errors="0">
  <testcase name="loginToJiraApiTest" time="1.31" classname="com.rest.services.test.JiraTests"/>
  <testcase name="createIssueInJiraApiTest" time="1.057" classname="com.rest.services.test.JiraTests">
    <failure type="java.lang.AssertionError" message="create issue in Jira failed due to">
      <![CDATA[java.lang.AssertionError: create issue in Jira failed due to
	at com.rest.services.test.JiraTests.createIssueInJiraApiTest(JiraTests.java:85)
Caused by: java.lang.AssertionError: The following asserts failed:
	expected [20] but found [201]
	at com.rest.services.test.JiraTests.createIssueInJiraApiTest(JiraTests.java:81)
	... 25 more
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- createIssueInJiraApiTest -->
</testsuite> <!-- Automation -->
